### PR TITLE
Web application for chating and explaining things via writing

### PR DESCRIPTION
**Pull request by nikhilgupta2001**
Hii there, I  created an app for chating and playing games like o and x and also can explain things via this app.
please have a look and let me know if any changes required.

### CODE REVIEW

**Comment by nikhilgupta2001** [comment]
please also give it hacktoberfest-accepted  tag if you find it useful.

**Comment by eika-sia** [comment]
Hey i see you have uploaded node_modules folder which is kinda hard to review, so could you add a commit without them or create a new PR with a .gitignore file?

**Comment by nikhilgupta2001** [comment]
I have Commited it with gitignore node_modules please have a look

**Comment by eika-sia** [comment]
This is really cool.

**Pull request merged**
