### PR TITLE
Simon Game with sounds

### PR DESCRIPTION
**Pull request by pshrimal000**

### CODE REVIEW

**Comment by GMCgit** [comment]
Hey, Could you add to your readme or here whats the game about and if you need credits somewhere

**Review by eika-sia — APPROVED** [review]
The game seems fun, I wouldn’t think of making that, it should be added in up to 12h, please send a comment if you need any credits

**Comment by pshrimal000** [comment]
No credits required buddy. Thanks for responding and accepting the pull
request so nice of you:)

**Comment by pshrimal000** [comment]
Also can u please add hacktoberfest-accepted label into pr so that it can
add in completing hacktober challenge:)

**Pull request merged**
